export const LEGACY_XAPI_DESCRIBE_MAP: Record<string, string[]> = {
  "XAPI-00002": ["An LRS stores 32-bit floating point numbers with at least the precision of IEEE 754"],
  "XAPI-00011": ["An LRS rejects with error code 400 Bad Request a Statement containing IRL or IRI values without a scheme."],
  "XAPI-00012": ["The LRS rejects with error code 400 Bad Request parameter values which do not validate to the same standards required for values of the same types in Statements"],
  "XAPI-00014": ["All Objects are well-created JSON Objects (Nature of binding, Data 2.1, XAPI-00014) **Implicit**"],
  "XAPI-00016": ["A Voiding Statement cannot Target another Voiding Statement", "An LRS SHALL NOT reject a voided statement because it cannot find the ID of the Object of that statement, nor does the LRS have to try to find it."],
  "XAPI-00018": ["A Voided Statement is defined as a Statement that is not a Voiding Statement and is the Target of a Voiding Statement within the LRS"],
  "XAPI-00023": ["A stored property must be a TimeStamp"],
  "XAPI-00064": ["An Activity Definition uses the \"interactionType\" property if any of the correctResponsesPattern, choices, scale, source, target, or steps properties are used (Multiplicity, Data 2.4.4.1.s8, XAPI-00064) **Implicit**"],
  "XAPI-00065": ["Statements that use an Agent or Group as an Object MUST specify an \"objectType\" property."],
  "XAPI-00096": ["An LRS returns a ContextActivity in an array, even if only a single ContextActivity is returned"],
  "XAPI-00097": ["An LRS MUST accept statements with the stored property"],
  "XAPI-00099": ["An LRS populates the \"authority\" property if it is not provided in the Statement, based on header information with the Agent corresponding to the user (contained within the header)"],
  "XAPI-00108": ["If not empty, the \"more\" property\\'s IRL refers to a specific container object corresponding to the next page of results from the orignal GET request"],
  "XAPI-00109": ["The \"more\" property is absent or an empty string (no whitespace) if the entire results of the original GET request have been returned."],
  "XAPI-00110": ["A \"statements\" property is an Array of Statements"],
  "XAPI-00113": ["An LRS\\'s Statement API, upon processing a successful GET request, will return a single \"statements\" property and a single \"more\" property."],
  "XAPI-00115": ["A Signed Statement MUST include a JSON web signature, JWS"],
  "XAPI-00116": ["The JWS signature MUST have a payload of a valid JSON serialization of the complete Statement before the signature was added."],
  "XAPI-00117": ["The JWS signature MUST use an algorithm of \"RS256\", \"RS384\", or \"RS512\"."],
  "XAPI-00119": ["An Extension can be null, an empty string, objects with nothing in them when using PUT."],
  "XAPI-00122": ["A Timestamp MUST preserve precision to at least milliseconds, 3 decimal points beyond seconds."],
  "XAPI-00125": ["An LRS responds to a HEAD request in the same way as a GET request, but without the message-body (Communication 1.1.s3.b1, XAPI-00125) **This means run ALL GET tests with HEAD**"],
  "XAPI-00126": ["An LRS accepts HEAD requests"],
  "XAPI-00127": ["An LRS rejects with error code 400 Bad Request, a Request which uses Attachments and does not have a \"Content-Type\" header with value \"application/json\" or \"multipart/mixed\""],
  "XAPI-00128": ["An LRS rejects with error code 400 Bad Request, a PUT or POST Request which has excess multi-part sections that are not attachments."],
  "XAPI-00129": ["An LRS rejects with error code 400 Bad Request, a PUT or POST Request which uses Attachments, has a \"Content-Type\" header with value \"application/json\", and has a discrepancy in the number of Attachments vs. the number of fileURL members"],
  "XAPI-00130": ["An LRS rejects with error code 400 Bad Request, a PUT or POST Request which uses Attachments, has a \"Content Type\" header with value \"multipart/mixed\", and does not have a Boundary before each \"Content-Type\" header"],
  "XAPI-00131": ["An LRS rejects with error code 400 Bad Request, a PUT or POST Request which uses Attachments, has a \"Content Type\" header with value \"multipart/mixed\", and does not have a body header named \"boundary\""],
  "XAPI-00132": ["An LRS rejects with error code 400 Bad Request, a PUT or POST Request which uses Attachments, has a \"Content Type\" header with value \"multipart/mixed\", and for any part except the first does not have a Header named \"X-Experience-API-Hash\" with a value of one of those found in a \"sha2\" property of a Statement in the first part of this document"],
  "XAPI-00133": ["An LRS rejects with error code 400 Bad Request, a PUT or POST Request which uses Attachments, has a \"Content Type\" header with value \"multipart/mixed\", and does not have all of the Statements in the first document part"],
  "XAPI-00134": ["An LRS rejects with error code 400 Bad Request, a PUT or POST Request which uses Attachments, has a \"Content Type\" header with value \"multipart/mixed\", and does not the first document part with a \"Content-Type\" header with a value of \"application/json\""],
  "XAPI-00139": ["An LRS has a Statement Resource with endpoint \"base IRI\"+\"/statements\""],
  "XAPI-00142": ["An LRS cannot modify a Statement, state, or Object in the event it receives a Statement with statementID equal to a Statement in the LRS already."],
  "XAPI-00143": ["An LRS\\'s Statement Resource upon processing a successful PUT request returns code 204 No Content"],
  "XAPI-00144": ["An LRS\\'s Statement Resource accepts PUT requests only if it contains a \"statementId\" parameter"],
  "XAPI-00145": ["An LRS\\'s Statement Resource accepts PUT requests only if it contains a \"statementId\" parameter"],
  "XAPI-00146": ["An LRS\\'s Statement Resource upon processing a successful POST request returns code 200 OK and all Statement UUIDs within the POST **Implicit**"],
  "XAPI-00147": ["An LRS\\'s Statement Resource accepts POST requests"],
  "XAPI-00149": ["The LRS will NOT reject a GET request which returns an empty \"statements\" property"],
  "XAPI-00150": ["An LRS\\'s Statement Resource rejects with error code 400 a GET request with both \"voidedStatementId\" and anything other than \"attachments\" or \"format\" as parameters"],
  "XAPI-00151": ["An LRS\\'s Statement Resource rejects with error code 400 a GET request with both \"statementId\" and anything other than \"attachments\" or \"format\" as parameters"],
  "XAPI-00153": ["An LRS\\'s Statement Resource upon processing a GET request, returns a header with name \"X-Experience-API-Consistent-Through\" regardless of the code returned."],
  "XAPI-00154": ["An LRS\\'s Statement Resource upon processing a successful GET request with neither a \"statementId\" nor a \"voidedStatementId\" parameter, returns code 200 OK and a StatementResult Object."],
  "XAPI-00155": ["An LRS\\'s Statement Resource upon processing a successful GET request with a \"voidedStatementId\" parameter, returns code 200 OK and a single Statement with the corresponding \"id\"."],
  "XAPI-00156": ["An LRS\\'s Statement Resource upon processing a successful GET request with a \"statementId\" parameter, returns code 200 OK and a single Statement with the corresponding \"id\"."],
  "XAPI-00157": ["An LRS\\'s Statement Resource can process a GET request with \"voidedStatementId\" as a parameter"],
  "XAPI-00158": ["An LRS\\'s Statement Resource can process a GET request with \"statementId\" as a parameter"],
  "XAPI-00159": ["LRS\\'s Statement Resource accepts GET requests"],
  "XAPI-00161": ["An LRSs Statement Resource does not return attachment data and only returns application/json if the \"attachment\" parameter set to \"false\""],
  "XAPI-00162": ["An LRS\\'s Statement Resource, upon processing a successful GET request wishing to return a Voided Statement still returns Statements which target it"],
  "XAPI-00163": ["An LRS\\'s Statement Resource, upon processing a successful GET request, can only return a Voided Statement if that Statement is specified in the voidedStatementId parameter of that request"],
  "XAPI-00164": ["The Statements within the \"statements\" property will correspond to the filtering criterion sent in with the GET request"],
  "XAPI-00165": ["An LRSs Statement Resource, upon receiving a GET request, MUST have a \"Content-Type\" header"],
  "XAPI-00166": ["An LRS\\'s Statement Resource can process a GET request with \"ascending\" as a parameter"],
  "XAPI-00167": ["An LRS\\'s Statement Resource can process a GET request with \"attachments\" as a parameter"],
  "XAPI-00172": ["If the \"Accept-Language\" header is present as part of the GET request to the Statement API and the \"format\" parameter is set to \"canonical\", the LRS MUST apply this data to choose the matching language in the response."],
  "XAPI-00173": ["An LRS\\'s Statement Resource can process a GET request with \"limit\" as a parameter"],
  "XAPI-00174": ["An LRS\\'s Statement Resource can process a GET request with \"until\" as a parameter"],
  "XAPI-00175": ["An LRS\\'s Statement Resource can process a GET request with \"since\" as a parameter"],
  "XAPI-00176": ["An LRS\\'s Statement Resource can process a GET request with \"related_agents\" as a parameter"],
  "XAPI-00178": ["An LRS\\'s Statement Resource can process a GET request with \"registration\" as a parameter"],
  "XAPI-00179": ["An LRS\\'s Statement Resource can process a GET request with \"activity\" as a parameter"],
  "XAPI-00180": ["An LRS\\'s Statement Resource can process a GET request with \"verb\" as a parameter"],
  "XAPI-00181": ["An LRS\\'s Statement Resource can process a GET request with \"agent\" as a parameter"],
  "XAPI-00196": ["An LRS\\'s State Resource rejects a DELETE request with \"agent\" as a parameter if it is not in JSON format with error code 400 Bad Request"],
  "XAPI-00197": ["An LRS\\'s State Resource rejects a GET request with \"agent\" as a parameter if it is not in JSON format with error code 400 Bad Request"],
  "XAPI-00198": ["An LRS\\'s State Resource rejects a POST request with \"agent\" as a parameter if it is not in JSON format with error code 400 Bad Request"],
  "XAPI-00200": ["An LRS\\'s State Resource rejects a DELETE request with \"registration\" as a parameter if it is not a UUID with error code 400 Bad Request"],
  "XAPI-00201": ["An LRS\\'s State Resource rejects a GET request with \"registration\" as a parameter if it is not a UUID with error code 400 Bad Request"],
  "XAPI-00202": ["An LRS\\'s State Resource rejects a POST request with \"registration\" as a parameter if it is not a UUID with error code 400 Bad Request"],
  "XAPI-00203": ["An LRS\\'s State Resource rejects a PUT request with \"registration\" as a parameter if it is not a UUID with error code 400 Bad Request"],
  "XAPI-00229": ["An LRSs State Resource, rejects a POST request if the document is found and either document is not a valid JSON Object"],
  "XAPI-00255": ["An LRS\\'s Agent Profile Resource rejects a DELETE request with \"agent\" as a parameter if it is not an Agent Object with error code 400 Bad Request"],
  "XAPI-00257": ["An LRS\\'s Agent Profile Resource rejects a PUT request with \"agent\" as a parameter if it is not an Agent Object with error code 400 Bad Request"],
  "XAPI-00258": ["An LRS\\'s Agent Profile Resource rejects a GET request with \"agent\" as a parameter if it is a valid, in structure, Agent with error code 400 Bad Request"],
  "XAPI-00260": ["An LRS\\'s Agent Profile Resource rejects a GET request with \"since\" as a parameter if it is not a \"TimeStamp\", with error code 400 Bad Request"],
  "XAPI-00278": ["An LRSs Agent Profile Resource, rejects a POST request if the document is found and either documents type is not \"application/json\" with error code 400 Bad Request"],
  "XAPI-00282": ["An LRS has an Agent Profile Resource with endpoint \"base IRI\"+\"/agents/profile\""],
  "XAPI-00287": ["An LRS\\'s Activity Profile Resource accepts PUT requests"],
  "XAPI-00293": ["An LRS\\'s Activity Profile Resource accepts PUT requests"],
  "XAPI-00295": ["An LRS\\'s Activity Profile Resource rejects a GET request with \"since\" as a parameter if it is not a \"TimeStamp\", with error code 400 Bad Request"],
  "XAPI-00313": ["An LRS\\'s Activity Profile Resource, rejects a POST request if the document is found and either document is not a valid JSON Object"],
  "XAPI-00321": ["An LRS rejects with error code 400 Bad Request, a Request which does not use a \"X-Experience-API-Version\" header name to any Resource except the About Resource"],
  "XAPI-00322": ["An LRS must support HTTP/1.1 entity tags (ETags) to implement optimistic concurrency control when handling Resources where PUT may overwrite existing data"],
  "XAPI-00325": ["An LRS rejects with error code 400 Bad Request any request to an Resource which uses a parameter with differing case"],
  "XAPI-00326": ["An LRS does not process any batch of Statements in which one or more Statements is rejected and if necessary, restores the LRS to the state in which it was before the batch began processing"],
  "XAPI-00330": ["An LRS will not modify Statements based on a \"version\" before \"1.0.1\""],
  "XAPI-00331": ["An LRS rejects with error code 400 Bad Request, a Request which does not use a \"X-Experience-API-Version\" header name to any Resource except the About Resource"],
  "XAPI-00334": ["An LRS rejects a Statement of bad authorization, either authentication needed or failed credentials, with error code 401 Unauthorized"],
  "XAPI-00336": ["The LRS MUST support the Alternate Request Syntax"],
};
